keys:
  - &emil age130l3j3gmn49kzjynemnlqkm5hnaghtkcayl2vkr7y65vy59deq0qt8f5dg

creation_rules:
  # SMB/CIFS credentials
  - path_regex: smb\.yaml$
    key_groups:
    - age:
      - *emil

  # System-wide secrets
  - path_regex: system\.yaml$
    key_groups:
    - age:
      - *emil
